# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "C:/blender-git/goo-engine;C:/blender-git/build_windows_x64_vc16_Release")
set(CPACK_CMAKE_GENERATOR "Visual Studio 16 2019")
set(CPACK_COMPONENTS_ALL "Blender;Libraries;Unspecified")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_CREATE_DESKTOP_LINKS "blender-launcher;Blender")
set(CPACK_DATE "")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Blender built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INSTALL_CMAKE_PROJECTS "C:/blender-git/build_windows_x64_vc16_Release;Blender;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files/")
set(CPACK_MODULE_PATH "C:/blender-git/goo-engine/build_files/cmake/Modules;C:/blender-git/goo-engine/build_files/cmake/platform")
set(CPACK_NSIS_COMPRESSOR "/SOLID lzma")
set(CPACK_NSIS_DISPLAY_NAME "Blender Foundation/Blender 3.3")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_MUI_ICON "C:/blender-git/goo-engine/release/windows/icons/winblender.ico")
set(CPACK_NSIS_PACKAGE_NAME "Blender Foundation/Blender 3.3")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "C:/blender-git/build_windows_x64_vc16_Release/CPackConfig.cmake")
set(CPACK_OVERRIDE_PACKAGENAME "")
set(CPACK_PACKAGE_CONTACT "foundation@blender.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "Blender is the free and open source 3D creation suite software.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Blender built using CMake")
set(CPACK_PACKAGE_EXECUTABLES "blender-launcher;Blender")
set(CPACK_PACKAGE_FILE_NAME "blender-3.3.2-git.a342799a152c-windows64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Blender Foundation/Blender 3.3")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Blender Foundation/Blender 3.3")
set(CPACK_PACKAGE_NAME "Blender")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Blender Foundation")
set(CPACK_PACKAGE_VERSION "3.3.2")
set(CPACK_PACKAGE_VERSION_MAJOR "3")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "2")
set(CPACK_RESOURCE_FILE_LICENSE "C:/blender-git/goo-engine/release/license/GPL-3.0.txt")
set(CPACK_RESOURCE_FILE_README "C:/Program Files/CMake/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-3.25/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/blender-git/build_windows_x64_vc16_Release/CPackSourceConfig.cmake")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "Windows")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Windows")
set(CPACK_WIX_LIGHT_EXTRA_FLAGS "-dcl:medium")
set(CPACK_WIX_PRODUCT_ICON "C:/blender-git/goo-engine/release/windows/icons/winblender.ico")
set(CPACK_WIX_SIZEOF_VOID_P "8")
set(CPACK_WIX_TEMPLATE "C:/blender-git/goo-engine/../lib/win64_vc15/package/installer_wix/WIX.template")
set(CPACK_WIX_UI_BANNER "C:/blender-git/goo-engine/../lib/win64_vc15/package/installer_wix/WIX_UI_BANNER.bmp")
set(CPACK_WIX_UI_DIALOG "C:/blender-git/goo-engine/../lib/win64_vc15/package/installer_wix/WIX_UI_DIALOG.bmp")
set(CPACK_WIX_UPGRADE_GUID "2C17F3FA-942E-5313-8805-21AB5B39513C")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/blender-git/build_windows_x64_vc16_Release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
